### ISSUE TITLE
Feature Request: Docker Version

### ISSUE THREAD

**Issue by albino1** [Colaski/global-streaming-search#1]
Hey there, very cool project and super useful.

I wonder if you would consider making a containerized docker version of Global Streaming Search.  The actual website only sometimes works, probably due to too many requests, so being able to run it locally via docker would be a big improvement and hopefully reduce the load on your server.

Thanks!

**Comment by Colaski** [comment]
Creating a docker container is something I have considered and have attempted to implement. The issue is that for some reason docker has an issue with Cross-origin resource sharing making a proxy server necessary just like the GitHub site (the proxies are the reason the website breaks from time to time). putting a server in docker is possible but it complicates the docker setup burden for the average user and is very easy to break. So, running it directly with npm will remain the only way to run locally for now.

I recently updated how the website load balances which should make the website much more reliable.

**Comment by albino1** [comment]
Ah, it's always more complicated than you think it's going to be.  Thanks for looking into it, and I appreciate the website upgrade.
