### ISSUE TITLE
Doesn t work

### ISSUE THREAD

**Issue by Spino10** [Colaski/global-streaming-search#11]
Hi global search doesn t work

**Comment by YariKandy** [comment]
Still Blank search 08.25 AM 05/12/2022[GMT +00:00

**Comment by Spino10** [comment]
Still blank now 6.12.22 11.22 european time

**Comment by YariKandy** [comment]
because still not working. I'm using it on my local PC. working fine. Install Git software & nodejs and run the command in the description. "Execute these commands in your terminal:" 
You can search on mobile using the Network address provided by cmd. need to open cmd all the time. it's fine. I just using when I want something to watch.

**Comment by Mancini316** [comment]
Page just shows blank when I search. Been like this for a week now. Any update on a fix?

**Comment by Colaski** [comment]
#15
